# sudo: false
# language: node_js
# node_js:
# - 10 # use nodejs v10 LTS
# cache: npm
# branches:
#   only:
#     - hexo # build hexo branch only
# script:
#   - hexo generate # generate static files
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GH_TOKEN
#   keep-history: true
# on:
#   all_branches: true # solve a permission problem
#   # branch: master
#   local-dir: public

sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: "./public"
  target_branch: master
  on:
    target_branch: master